import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Cards from "@/components/cards";
import data from "@/data/data";
import { Button } from "react-bootstrap";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  var datas = ["a", "b", "c"];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <img src={"/logo.png"} />
        <h1>phincon</h1>
        {/* <Cards name={"asdasd"} age={"123123"} /> */}

        {/* {datagabung.map((data) => (
          <Cards age={data} />
        ))} */}
        {/* alt + shift + f */}
        {data.datagabung.map((data) =>
          data === 123 ? (
            <b>
              <Cards age={data} />
            </b>
          ) : (
            <></>
          )
        )}
        <p>{JSON.stringify(data.dataMapGabung, null, 2)}</p>
        <Link href="/articles">
          <Button>Go to Articles</Button>
        </Link>
      </main>
    </>
  );
}
